### ISSUE TITLE
Add more safety checks in MEM_InitGlobalInst

### ISSUE THREAD

**Issue by szapp** [Lehona/Ikarus#16]
If Ikarus is initialization from `InitPerceptions` (in order to use Ikarus before the main menu is reached), it raises null pointer warnings for `MEM_InfoMan` and `MEM_SpawnManager` in Gothic 1.

Like the "recent" change to wrap `MEM_Camera` and `MEM_SkyController` into null pointer checks (see 33157f2), this should be done here too.

**Comment by Lehona** [comment]
Closed via #17
