### ISSUE TITLE
Fix hex conversions

### ISSUE THREAD

**Issue by szapp** [Lehona/Ikarus#19]
The function [MEMINT_HexCharToInt](https://github.com/Lehona/Ikarus/blob/704dad8249148b02e0482d2350e4afcbb2d622a0/Ikarus.d#L4465-L4476) does not take capital characters into account and the function [MEMINT_ByteToKeyHex](https://github.com/Lehona/Ikarus/blob/704dad8249148b02e0482d2350e4afcbb2d622a0/Ikarus.d#L4516-L4526) fails for digits larger than `0x9`.

The first can be fixed by a simple lower case conversion (it's time we finally complement the `STR_Upper` function with a `STR_Lower` function) and the latter by the following lines of code (taken from `byte2hex` in ScriptBin/convert.d).
```diff
 func string MEMINT_ByteToKeyHex(var int byte) {
     const int ASCII_0 = 48;
+    const int ASCII_A = 65;
     byte = byte & 255;
+ 
+    // Fix ASCII characters (A to F)
+    var int c1; c1 = (byte >> 4);
+    if (c1 >= 10) {
+        c1 += ASCII_A-ASCII_0-10;
+    };
+    var int c2; c2 = (byte & 15);
+    if (c2 >= 10) {
+        c2 += ASCII_A-ASCII_0-10;
+    };
 
     const int mem = 0;
     if (!mem) { mem = MEM_Alloc(3); };
 
-    MEM_WriteByte(mem    , (byte >>  4) + ASCII_0);
-    MEM_WriteByte(mem + 1, (byte &  15) + ASCII_0);
+    MEM_WriteByte(mem    , c1 + ASCII_0);
+    MEM_WriteByte(mem + 1, c2 + ASCII_0);
     return STR_FromChar(mem);
 };
```

**Comment by Lehona** [comment]
Fixed via #20
