### ISSUE TITLE
Ikarus_Const_G1 incorrect vtbl values

### ISSUE THREAD

**Issue by Fawkes-dev** [Lehona/Ikarus#24]
```c++
zCRoute_vtbl = 8252184; //8252184 is actually 0x007DEB18 zCWaypoint_vtbl, correct value is 8252208 007DEB30
zCZoneMusic_vtbl = 8252476; //8252476 is actually 0x007DEC3C oCZoneMusic_vtbl, correct value is 8242628 007DC5C4
zCCSManager_vtbl = 8194068; //8194068 is actually 0x007D0814 oCCSManager_vtbl, correct value is 8195652 007D0E44
zCDecal_vtbl = 8241804;	//8241804 is actually 0x007DC28C zCZoneZFogDefault_vtbl, correct value is 8207876 007D3E04
```
Here is list of all vtbl constants, maybe can be useful:
[G2A all vtbl values - Copy.xlsx](https://github.com/Lehona/Ikarus/files/6447240/G2A.all.vtbl.values.-.Copy.xlsx)
[G1 all vtbl values - Copy.xlsx](https://github.com/Lehona/Ikarus/files/6447241/G1.all.vtbl.values.-.Copy.xlsx)

**Comment by szapp** [comment]
Thanks for that list!

I think Ikarus is now only being changed for critical bug fixing. I think that any additions or a new version of Ikarus are (at this point) very unlikely.

**Comment by Fawkes-dev** [comment]
Ok, I will try to use local constants in my methods then :)
